image: docker.io/reclaimthestack/rails-example:latest
deployments:
  web:
    replicas: 2
    memory: 512Mi
    cpu: 250m
    env:
      - name: WEB_CONCURRENCY
        value: "2"
    readinessProbePath: /up # when this path returns 200 the pod will be considered ready
  sidekiq:
    replicas: 1
    memory: 512Mi
    cpu: 250m
    env: [] # Put ENV which should only apply to the sidekiq deployment here
resources:
  postgres:
    replicas: 2
    memory: 1Gi
    cpu: 1
    disk: 10Gi
    # Tip: generate configuration based on CPU / RAM settings at https://pgtune.leopard.in.ua/
    config:
      max_connections: "40"
      shared_buffers: 256MB
      effective_cache_size: 768MB
      maintenance_work_mem: 64MB
      checkpoint_completion_target: "0.9"
      wal_buffers: 7864kB
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: 3276kB
      min_wal_size: 1GB
      max_wal_size: 4GB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: top
  redis:
    sentinels: 3
    replicas: 2
    memory: 100Mi # must use Gi or Mi format
    cpu: 250m
    disk: 500Mi
  elasticsearch:
    replicas: 2 # Note: 2 replicas will also add a small third tiebreaker node
    memory: 1Gi # Provide at least 1Gi of RAM to avoid OOM kills
    cpu: 1
    disk: 10Gi
envFrom:
  - secretRef:
      name: rails-example-staging
env:
  - { name: DATABASE_URL, valueFrom: { secretKeyRef: { name: rails-example-staging-app, key: uri } } }
  - { name: REDIS_URL, value: "redis://rails-example-staging-redis-master.default.svc:6379" }
  - { name: ELASTICSEARCH_PASSWORD, valueFrom: { secretKeyRef: { name: rails-example-staging-es-elastic-user, key: elastic } } }
  - { name: ELASTICSEARCH_URL, value: "http://elastic:$(ELASTICSEARCH_PASSWORD)@rails-example-staging-es-http:9200" }
