---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgBuYJHznSbh+Whk8iQdEl65LPR/Q9QoaydrCNs07S+BWTQ1yVGcYBfJDVO5kAeuz3nxCI2IesWo2eOsRS2ug3zOr0euvOMX/hiEkdCO45zXv35KK+PvVTuyVoN5GhAh0JYCU9gftiWJ0sEsgWmJuHNdwxTS2TnoIXynOokmyEqij6qjxe9153CAixfPAXHyoA6DB2OIPA2m8Q/dYeFrkjdv90ARnI3Je71tryJlfAVpJlr9Aaujv8Zw79iEmT2YmqnLxaGHEWf1S8OWH7Yx6KpIW8foHLqfaqQUbLhuS4eOlv8M/g3RxdW+Re80pK4IJ3gLon0vGgOUxXH26jjdMIVwg5elJNROa+SlOS8UDkl0zghGJxmxkw9jgkFHWjQAPfacJOBQC1FZNzXIcwcJMeuNf2lj4e5TgsZ+c9drk4JfVjL6x1WVAx2N6xM/dO10lNSpP/CVFgOXo1TPy1z55HLHPD2pmBAdqVSsPtcwkeplm//UnEUUQuqywRO/5rWHX5CBYz5uyA20aum8KTIhfgGVqR8Nro9mTRMUtQXDhLPTBY+vDqKqysYlhX0W/zwxkOBFboWTRdfA9z2iBHz/wCp+7xzXc4ilhMMFZbNN5QCXMEoMPZzk5LlCc6Ed4mdxAXahjrsnglHxMhNqBHeutOy4e6Ct6qi/7deZGpOerxCGvFobF/XIfGfBbH/tzn+KC9SV+vTIp4t8JlbD/4vR8WHAMlgaW3atFH4ThirBmnGYXyRlns0DFvqV+GCDNzB421EaT3RvzcmKkQ850UTU4O73ASyxPfCDzYlQw/B+iTumki0DSstJwPwCwayD33JZnth9jvHDLGVX4+a2J5aTMpT30FJbg2KvPXv6A7APcDoIH3GBDSYpp/oL5L+0Ki3M4kGT6av2nOdb47bR7BOJaXcVUQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
