apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: platform
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    # Changelog at https://github.com/bitnami-labs/sealed-secrets/blob/main/RELEASE-NOTES.md
    targetRevision: 2.15.4 # sealed-secrets v0.26.3
    helm:
      parameters:
        # Fix helm chart compatibility with kubeseal
        - name: fullnameOverride
          value: sealed-secrets-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
